version: '3.8'

services:
  db:
    platform: linux/amd64
    image: mysql:8.0.39
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: wakatter_sample_development
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_OPTIONS: --openssl-legacy-provider
      DATABASE_HOST: db
      DATABASE_USERNAME: root
      DATABASE_PASSWORD:
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    command: ["bash", "-c", "rm -f tmp/pids/server.pid && ./bin/webpack-dev-server & bundle exec rails server -b 0.0.0.0"]
    ports:
      - "3000:3000"
      - "3035:3035"
    depends_on:
      - db
    volumes:
      - .:/app
      - gems:/gems

volumes:
  db_data:
  gems:
