global.$ = global.jQuery = require('jquery')
require("@rails/ujs").start()
require("turbolinks").start()
require("@rails/activestorage").start()
require("./image_uploader")
require("./header_dropdown")
require("./dm_textarea")
